using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid;
using DevExpress.XtraEditors.Controls;

namespace MTAutomation
{

    public partial class MTAutomation : Form
    {

        private MTProviderEntities db = new MTProviderEntities();
        private string symbol = "";
        public MTAutomation()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //MTProviderEntities dbContext = new MTProviderEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //db.MTSymbols.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    mTSymbolsBindingSource.DataSource = db.MTSymbols.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void FillPositions()
        {
            IList<PositionsDTO> positions = (from p in db.Positions
                                             join s in db.MTSymbols on p.SymbolName equals s.Name
                                             where p.IsClose == false && p.TicketNo != 0
                                             orderby p.PositionState ascending
                                             select new PositionsDTO
                                             {
                                                 ID = p.ID,
                                                 RowNO = p.RowNO,
                                                 PositionStateStr = !p.PositionState ? "Buy" : "Sell",
                                                 Volume = p.Volume,
                                                 SymbolName = p.SymbolName,
                                                 MarketPrice = !p.PositionState ? s.BidPrice : s.AskPrice,
                                                 Profit = !p.PositionState ? (s.BidPrice - p.Price) * p.Volume * 100000 * s.PerUSDAsk : (p.Price - s.AskPrice) * p.Volume * 100000 * s.PerUSDBid,
                                                 ProfitPercent = (!p.PositionState ? (s.BidPrice - p.Price) * p.Volume * 100000 * s.PerUSDAsk : (p.Price - s.AskPrice) * p.Volume * 100000 * s.PerUSDBid) / (p.Volume * 100000 * p.PriceInUSD / p.Leverage) * 100,
                                                 Price = p.Price,
                                                 UserName = p.UserName,
                                                 Leverage = p.Leverage
                                             }).ToList();

            dgwOpenPosition.AutoGenerateColumns = false;
            dgwOpenPosition.DataSource = positions;


            IList<PositionsDTO> closePositions = (from p in db.Positions
                                                  join s in db.MTSymbols on p.SymbolName equals s.Name
                                                  where p.IsClose == true && p.TicketNo != 0
                                                  orderby p.PositionState ascending
                                                  select new PositionsDTO
                                                  {
                                                      ID = p.ID,
                                                      RowNO = p.RowNO,
                                                      PositionStateStr = !p.PositionState ? "Buy" : "Sell",
                                                      Volume = p.Volume,
                                                      SymbolName = p.SymbolName,
                                                      MarketPrice = !p.PositionState ? s.BidPrice : s.AskPrice,
                                                      Profit = !p.PositionState ? (s.BidPrice - p.Price) * p.Volume * 100000 * s.PerUSDAsk : (p.Price - s.AskPrice) * p.Volume * 100000 * s.PerUSDBid,
                                                      ProfitPercent = (!p.PositionState ? (s.BidPrice - p.Price) * p.Volume * 100000 * s.PerUSDAsk : (p.Price - s.AskPrice) * p.Volume * 100000 * s.PerUSDBid) / (p.Volume * 100000 * p.PriceInUSD / p.Leverage) * 100,
                                                      Price = p.Price,
                                                      UserName = p.UserName,
                                                      Leverage = p.Leverage
                                                  }).ToList();

            dgwClosePosition.AutoGenerateColumns = false;
            dgwClosePosition.DataSource = closePositions;
        }

        private void MTAutomation_Load(object sender, EventArgs e)
        {
            FillPositions();

            List<MTSymbol> symbols = db.MTSymbols.Include("MTHistoryMS").ToList();
            BindingList<MTSymbol> bindingSymbols = new BindingList<MTSymbol>(symbols);
            gvControlHistory.DataSource = bindingSymbols;
            //gvControlHistory.DataSource = symbols;
            gvDetailHistory.OptionsBehavior.AllowAddRows = DevExpress.Utils.DefaultBoolean.False;

            repositoryItemLookUpEdit1.DataSource = db.MTPeriods.ToList();
            repositoryItemLookUpEdit1.DisplayMember = "PeriodName";
            repositoryItemLookUpEdit1.ValueMember = "PeriodID";

        }

        private void gvlHistory_MasterRowGetRelationName(object sender, DevExpress.XtraGrid.Views.Grid.MasterRowGetRelationNameEventArgs e)
        {
            e.RelationName = "MTHistoryMS";
        }

        private void gvlHistory_MasterRowGetChildList(object sender, DevExpress.XtraGrid.Views.Grid.MasterRowGetChildListEventArgs e)
        {
            GridView view = sender as GridView;
            MTSymbol c = (MTSymbol)view.GetRow(e.RowHandle);
            BindingList<MTHistoryM> bindingHistory = new BindingList<MTHistoryM>(c.MTHistoryMS.ToList());
            e.ChildList = bindingHistory;
            //e.ChildList = c.MTHistoryMS.ToList();
        }

        private void gvlHistory_MasterRowGetRelationCount(object sender, MasterRowGetRelationCountEventArgs e)
        {
            e.RelationCount = 1;
        }

        private void gvDetailHistory_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            GridView view = sender as GridView;
            if (view.IsNewItemRow(e.RowHandle))
            {
                //view.ValidateEditor();
                MTHistoryM c = (MTHistoryM)e.Row;
                symbol = c.Symbol;
                db.MTHistoryMS.Add((MTHistoryM)e.Row);
                //view.CollapseGroupRow(view.SourceRowHandle);
            }
        }

        private void gvDetailHistory_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            GridView view = sender as GridView;
            view.SetRowCellValue(e.RowHandle, view.Columns["Symbol"], symbol);
            view.SetRowCellValue(e.RowHandle, view.Columns["AutoBuySell"], false);

            //view.FocusedColumn = view.VisibleColumns[0];
            //gvDetailHistory.FocusedRowHandle = e.RowHandle;//DevExpress.XtraGrid.GridControl.NewItemRowHandle;
            //gvDetailHistory.FocusedColumn = gvDetailHistory.VisibleColumns[0];
        }

        private void gvlHistory_MasterRowExpanded(object sender, CustomMasterRowEventArgs e)
        {
            GridView view = sender as GridView;
            MTSymbol c = (MTSymbol)view.GetRow(e.RowHandle);

            GridView childView = view.GetDetailView(e.RowHandle, e.RelationIndex) as GridView;
            if (childView != null)
            {
                symbol = c.Name;
                childView.AddNewRow();
            }

        }

        private void button2_Click(object sender, EventArgs e)
        {
            db.SaveChanges();
        }

        private void gvDetailHistory_ShownEditor(object sender, EventArgs e)
        {
            GridView view = sender as GridView;
            view.ActiveEditor.IsModified = true;
        }

        private void gvDetailHistory_ValidatingEditor(object sender, DevExpress.XtraEditors.Controls.BaseContainerValidateEditorEventArgs e)
        {
            GridView gv = (sender as GridView);

            if (gv.FocusedColumn.FieldName == coldtStartTime.FieldName)
            {
                DateTime date = new DateTime();
                //var value = gv.GetRowCellValue(gv.FocusedRowHandle, coldtStartTime);
                if (e.Value == null)
                {
                    e.Valid = false;
                    e.ErrorText = "Start Time can't be empty";
                }
                else
                {
                    if (String.IsNullOrEmpty(e.Value.ToString()))
                    {
                        e.Valid = false;
                        e.ErrorText = "Start Time can't be empty";
                    }
                    else
                    {
                        if (!DateTime.TryParse(e.Value.ToString(), out date))
                        {
                            e.Valid = false;
                            e.ErrorText = "Start Time isn't valid date";
                        }
                    }
                }

            }
            if (gv.FocusedColumn.FieldName == coldtPeriod.FieldName)
            {
                if (e.Value == null)
                {
                    e.Valid = false;
                    e.ErrorText = "Please select one item";
                }
                else
                {
                    if (String.IsNullOrEmpty(e.Value.ToString()))
                    {
                        e.Valid = false;
                        e.ErrorText = "Please select one item";
                    }
                    else
                    {
                        bool valid = true;
                        for (int i = 0; i < gv.DataRowCount; i++)
                        {
                            //valid = false;
                            //foreach (GridColumn column in gv.Columns)
                            //{

                            if (i != gv.FocusedRowHandle)
                            {
                                if (gv.GetRowCellValue(i, coldtPeriod).Equals(e.Value))
                                {
                                    //valid = true;
                                    valid = false;
                                    break;
                                }
                            }
                            //}
                            //if (!valid) break;
                        }
                        if (!valid)
                        {
                            e.Valid = false;
                            e.ErrorText = "Please select another period, this period is duplicated";
                        }
                    }
                }
            }
        }

        private void gvDetailHistory_ValidateRow(object sender, DevExpress.XtraGrid.Views.Base.ValidateRowEventArgs e)
        {
            GridView gv = (sender as GridView);

            DateTime date = new DateTime();
            var valueTime = gv.GetRowCellValue(e.RowHandle, coldtStartTime);
            var valuePeriod = gv.GetRowCellValue(e.RowHandle, coldtPeriod);
            if (valueTime == null)
            {
                e.Valid = false;
                e.ErrorText = "Start Time can't be empty";
            }
            else
            {
                if (String.IsNullOrEmpty(valueTime.ToString()))
                {
                    e.Valid = false;
                    e.ErrorText = "Start Time can't be empty";
                }
                else
                {
                    if (!DateTime.TryParse(valueTime.ToString(), out date))
                    {
                        e.Valid = false;
                        e.ErrorText = "Start Time isn't valid date";
                    }
                }
            }

            if (valuePeriod == null)
            {
                e.Valid = false;
                e.ErrorText = "Please select one item";
            }
            else
            {
                if (String.IsNullOrEmpty(valuePeriod.ToString()))
                {
                    e.Valid = false;
                    e.ErrorText = "Please select one item";
                }
                else
                {

                    bool valid = true;
                    for (int i = 0; i < gv.DataRowCount; i++)
                    {
                        //valid = false;
                        //foreach (GridColumn column in gv.Columns)
                        //{
                        if (i != e.RowHandle)
                        {
                            if (gv.GetRowCellValue(i, coldtPeriod).Equals(gv.GetRowCellValue(e.RowHandle, coldtPeriod)))
                            {
                                //valid = true;
                                valid = false;
                                break;
                            }
                        }
                        //}
                        //if (!valid) break;
                    }
                    if (!valid)
                    {
                        e.Valid = false;
                        e.ErrorText = "Please select another period, this period is duplicated";
                    }
                }
            }

        }

        private void button1_Click(object sender, EventArgs e)
        {
            FillPositions();
        }

        private void gvControlHistory_ProcessGridKey(object sender, KeyEventArgs e)
        {
            GridControl grid = sender as GridControl;
            GridView view = grid.FocusedView as GridView;
            if (view.Name.Equals("gvDetailHistory"))
                if (e.KeyData == Keys.Delete)
                {
                    db.MTHistoryMS.Remove((MTHistoryM)view.GetRow(view.GetSelectedRows()[0]));
                    view.DeleteSelectedRows();
                    e.Handled = true;
                }
        }

        private void gvDetailHistory_InvalidRowException(object sender, DevExpress.XtraGrid.Views.Base.InvalidRowExceptionEventArgs e)
        {
            GridView gv = (sender as GridView);

            var valueTime = gv.GetRowCellValue(e.RowHandle, coldtStartTime);
            var valuePeriod = gv.GetRowCellValue(e.RowHandle, coldtPeriod);
            if (valueTime == null && valuePeriod == null)
            {
                e.ExceptionMode = ExceptionMode.Ignore;
            }
        }
    }
}
