//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTHistoryDT
    {
        public byte[] ID { get; set; }
        public Nullable<short> MSID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> Close { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Volume { get; set; }
    
        public virtual MTHistoryM MTHistoryM { get; set; }
    }
}
