//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTHistoryM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTHistoryM()
        {
            this.MTHistoryDTs = new HashSet<MTHistoryDT>();
        }
    
        public short ID { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<bool> AutoBuySell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTHistoryDT> MTHistoryDTs { get; set; }
        public virtual MTPeriod MTPeriod { get; set; }
        public virtual MTSymbol MTSymbol { get; set; }
    }
}
