//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTPeriod()
        {
            this.MTHistoryMS = new HashSet<MTHistoryM>();
        }
    
        public int PeriodID { get; set; }
        public string PeriodName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTHistoryM> MTHistoryMS { get; set; }
    }
}
