//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTSymbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTSymbol()
        {
            this.MTHistoryMS = new HashSet<MTHistoryM>();
        }
    
        public string Name { get; set; }
        public Nullable<double> AskPrice { get; set; }
        public Nullable<double> BidPrice { get; set; }
        public Nullable<double> PerUSDAsk { get; set; }
        public Nullable<double> PerUSDBid { get; set; }
        public string ChngFromUSDSymbol { get; set; }
        public string ChngToUSDSymbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTHistoryM> MTHistoryMS { get; set; }
    }
}
