//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public long ID { get; set; }
        public int RowNO { get; set; }
        public Nullable<int> TicketNo { get; set; }
        public string SymbolName { get; set; }
        public double Volume { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> PositionStatus { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public bool PositionState { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> ClosePrice { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public short Leverage { get; set; }
        public Nullable<double> PriceInUSD { get; set; }
        public string PriceInUSDSymbol { get; set; }
    }
}
